services:
    ldapClient:
        class: Symfony\Component\Ldap\LdapClient
        arguments:
            - %ldap.host% #Address to LDAPServer
            - %ldap.port% #Port where LDAPServer is listening
            - %ldap.version% #LDAP Protocol version
            - false           # SSL #Use SSL
            - false        # TLS 'Use TLS

    ext_ldap_user_provider:
            class: Wheregroup\Component\LdapMultiEncoderUserProvider
            arguments:
                - @ldapClient
                - %ldap.user.baseDn%
                - %ldap.bind.dn%
                - %ldap.bind.pwd%
                - [ROLE_USER]
                - %ldap.user.nameAttribute%
                - %ldap.user.query% #dn
                - %ldap.group.baseDn%
                - %ldap.group.query%
                - %ldap.group.nameattribute%

security:

    encoders:
      FOM\UserBundle\Entity\User: sha512
      plaintext:
           algorithm: plaintext
      SHA512:
          algorithm: sha512
          iterations: 1






    providers:
      ldapProvider:
        id: ext_ldap_user_provider
          # More options:
          # http://symfony.com/doc/2.8/security/ldap.html

          #filter: %ldap_user_search_filter%
      main:
        entity:
          class: FOM\UserBundle\Entity\User
          property: username
      chain_provider:
        chain:
          providers: ["main","ldapProvider"]






    acl:
        connection: default

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/user/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            provider: chain_provider
            form_login_ldap:

                check_path: /user/login/check
                login_path: /user/login
                service:  ldapClient

            form_login:
              check_path: /user/login/check
              login_path: /user/login
            logout:
                path:   /user/logout
                target: /


    access_control:
        - { path: ^/user/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manager,       roles: ROLE_USER }